### PR TITLE
Initial revision of the SerialConfig example that demonstrates how to…

### PR DESCRIPTION
**Pull request by petebrink**
… manipulate the configuration of the serial port using the CPP API.

### CODE REVIEW

**Comment by shnewto** [comment]
Not compiling on the current build.

**Comment by petebrink** [comment]
It needs the changes from the CPP API that have not been approved yet.

**Comment by shnewto** [comment]
oh I let that one slip after reviewing it, I've approved the API changes. When they're merged I'll revisit this.

**Comment by shnewto** [comment]
I closed this PR because the example is broken until we have a public API that supports it.

**Pull request closed without merging**
